baseURL = 'https://yihaow.com/'
languageCode = 'en-us'
title = 'Yihao Wu | PhD Student, UCSB'
theme = 'wyh_card_style'

disableKinds = ["taxonomy", "term"]

[params]
  profilePhoto = "/images/wyh.jpg"
  name_cn = "吴逸豪"
  name_en = "Yihao Wu"
  position = "PhD Student"
  company = " University of California, Santa Barbara"

[params.social]
  email = "yihao_wu@ucsb.edu"
  scholar = "https://scholar.google.com/citations?user=1hvJRIQAAAAJ&hl"
  linkedin = "https://www.linkedin.com/in/yihao-wu-a91474255/"
  orcid = "https://orcid.org/0009-0003-5126-0961"

